// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Entities;

public partial class User
{
    public int Id { get; set; }
    [EmailAddress]
    [Required]
    public string UserEmail { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
    [Required]
    public string Password { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}